
######################## default configuration ####################
baseURL = "https://sg.com.mx"
title = "SG Virtual Conference"
enableRobotsTXT = true
DefaultContentLanguage = "es"


theme = "vixcon-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "vixcon" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"

############################## navigation ###############################


#################### default parameters ################################
[params]
logo = "images/logo.jpg"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# email address
email = "demo@vixcon.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# search for blog page
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Regístrate"
link = "register"



############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://facebook.com/softwareguru"

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/RevistaSG"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://youtube.com/user/RevistaSG"

[[params.footer_links]]
name = "Best Place to Code"
link = "https://bestplacetocode.com"

[[params.footer_links]]
name = "Data Day"
link = "https://sg.com.mx/dataday"

[[params.footer_links]]
name = "Dev Day 4 Women"
link = "https://devday4w.com"

[[params.footer_links]]
name = "Developer Relations"
link = "https://devrel.sg.com.mx"

################################### English language #####################################

[languages]
################################### English language #####################################

  [languages.es]
    languageName = "Español"
    languageCode = "es-mx"
    contentDir = "content/es-mx"
    weight = 1
    home = "Inicio"
    footer_content = "Es otro fantástico evento de [Software Guru](https://sg.com.mx). <br>SG es el medio preferido por las personas de habla hispana interesadas en construir software de alto desempeño."

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    contentDir = "content/en-us"
    weight = 2
    home = "Home"
    footer_content = "We are a creative-led experiential Event Production Agency that helps brands connect, engage and evolve."



